### PR TITLE
Changed Dutch string to English.

### PR DESCRIPTION
**Pull request by Hexmage**

### CODE REVIEW

**Comment by JKingma** [comment]
@dpdplugin When will you release a new version with this comit?

**Comment by RemcoWolterink** [comment]
@dpdplugin can you give me an update on this? We are waiting on this.

**Comment by JKingma** [comment]
Anyone here?

**Comment by dpdplugin** [comment]
We will do a new release next week, all the pull requests will be considered by then.

**Comment by JKingma** [comment]
@dpdplugin thanks for this information!

**Pull request merged**
